pipeline {
  agent any
  options {
    disableConcurrentBuilds()
    disableResume()
    buildDiscarder(logRotator(numToKeepStr: '10'))
    timeout(time: 1, unit: 'HOURS')
  }
  parameters {
    booleanParam(name: 'TERRAFORM_APPLY', defaultValue: false, description: 'Apply Terraform changes ?')
    booleanParam(name: 'DESTROY_ON_FAILURE', defaultValue: true, description: 'Destroy the created resources on failure ?')
    booleanParam(name: 'PRINT_SSH_KEY', defaultValue: true, description: 'Want to print the private ssh key ?')
  }
  environment {
    TF_ROOT = "jenkins/azure-vm"
  }
  stages {
    stage('Generate SSH keys') {
      steps {
        dir("${env.TF_ROOT}") {
          sh """#!/bin/bash
            ssh-keygen -q -t rsa -N '' -f ./jenkins <<<y >/dev/null 2>&1
          """
          if(params.PRINT_SSH_KEY == true){
            sh "cat jenkins"
          }
        }
      }
    }
    stage('Get Azure Resourse group name') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'azure-credential', usernameVariable: 'AZURE_USERNAME', passwordVariable: 'AZURE_PASSWORD')]) {
          sh 'az login -u ${AZURE_USERNAME} -p ${AZURE_PASSWORD} --output none'
        }
        script {
          env.RG_NAME = sh(script: "az group list --query \"[0].name\" --out tsv", returnStdout: true).trim()
          echo "Azure Resource group name is : ${RG_NAME}"
        }
      }
    }
    stage('Terraform Init') {
      steps {
        dir("${env.TF_ROOT}") {
          sh "terraform init -no-color"
        }
      }
    }
    stage('Terraform Plan') {
      steps {
        dir("${env.TF_ROOT}") {
          sh "terraform plan -var 'resource_group_name=${env.RG_NAME}' -out=tfplan -no-color"
        }
      }
    }
    stage('Terraform Apply') {
      when {
        expression { params.TERRAFORM_APPLY == true }
      }
      steps {
        dir("${env.TF_ROOT}") {
          sh "terraform apply tfplan -no-color"
        }
      }
      post {
        failure {
          script {
            if(params.DESTROY_ON_FAILURE == true){
              dir("${env.TF_ROOT}") {
                sh "terraform destroy -no-color"
              }
            }
          }
        }
      }
    }
    stage('Terraform Output') {
      when {
        expression { params.TERRAFORM_APPLY == true }
      }
      steps {
        dir("${env.TF_ROOT}") {
          sh "terraform output -no-color"
        }
      }
    }
  }
  post {
    always {
      deleteDir()
    }
  }
}
